version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/devoteme
      - JWT_SECRET=dev-secret-key-change-in-production
      - PORT=3000
      - FRONTEND_URL=http://localhost:3001
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devoteme
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

